import {Movie} from './models'

export const SORT_ARIA_DIRECTIONS = {
  ASCENDING: 'ascending',
  DESCENDING: 'descending',
  OTHER: 'other',
  NONE: 'none',
}

export const HEADERS = [
  {
    header: 'Назва',
    accessorKey: 'title',
  },
  {header: 'Режисер', accessorKey: 'director'},
  {header: 'Рейтинг', accessorKey: 'rating'},
  {header: 'Рік випуску', accessorKey: 'releaseYear'},
]

export const MOVIES = [
  new Movie({
    title: 'Початок',
    director: 'Крістофер Нолан',
    releaseYear: 2010,
    runtimeMinutes: 148,
    genre: 'Наукова фантастика',
    rating: 8.8,
    boxOfficeMillions: 829.9,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Хрещений батько',
    director: 'Френсіс Форд Коппола',
    releaseYear: 1972,
    runtimeMinutes: 175,
    genre: 'Кримінал',
    rating: 9.2,
    boxOfficeMillions: 246,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Кримінальне чтиво',
    director: 'Квентін Тарантіно',
    releaseYear: 1994,
    runtimeMinutes: 154,
    genre: 'Кримінал',
    rating: 8.9,
    boxOfficeMillions: 213.9,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Втеча з Шоушенка',
    director: 'Френк Дарабонт',
    releaseYear: 1994,
    runtimeMinutes: 142,
    genre: 'Драма',
    rating: 9.3,
    boxOfficeMillions: 58.3,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Темний лицар',
    director: 'Крістофер Нолан',
    releaseYear: 2008,
    runtimeMinutes: 152,
    genre: 'Бойовик',
    rating: 9.0,
    boxOfficeMillions: 1004.9,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Форрест Гамп',
    director: 'Роберт Земекіс',
    releaseYear: 1994,
    runtimeMinutes: 142,
    genre: 'Драма',
    rating: 8.8,
    boxOfficeMillions: 678.2,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Бійцівський клуб',
    director: 'Девід Фінчер',
    releaseYear: 1999,
    runtimeMinutes: 139,
    genre: 'Драма',
    rating: 8.8,
    boxOfficeMillions: 101.2,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Інтерстеллар',
    director: 'Крістофер Нолан',
    releaseYear: 2014,
    runtimeMinutes: 169,
    genre: 'Наукова фантастика',
    rating: 8.6,
    boxOfficeMillions: 677.5,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Гладіатор',
    director: 'Рідлі Скотт',
    releaseYear: 2000,
    runtimeMinutes: 155,
    genre: 'Бойовик',
    rating: 8.5,
    boxOfficeMillions: 460.5,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Матриця',
    director: 'Лана Вачовскі, Ліллі Вачовскі',
    releaseYear: 1999,
    runtimeMinutes: 136,
    genre: 'Наукова фантастика',
    rating: 8.7,
    boxOfficeMillions: 466.3,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Володар перснів: Повернення короля',
    director: 'Пітер Джексон',
    releaseYear: 2003,
    runtimeMinutes: 201,
    genre: 'Фентезі',
    rating: 8.9,
    boxOfficeMillions: 1142,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Титанік',
    director: 'Джеймс Кемерон',
    releaseYear: 1997,
    runtimeMinutes: 195,
    genre: 'Драма',
    rating: 7.9,
    boxOfficeMillions: 2187,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Зелена миля',
    director: 'Френк Дарабонт',
    releaseYear: 1999,
    runtimeMinutes: 189,
    genre: 'Драма',
    rating: 8.6,
    boxOfficeMillions: 286.8,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Список Шиндлера',
    director: 'Стівен Спілберг',
    releaseYear: 1993,
    runtimeMinutes: 195,
    genre: 'Драма',
    rating: 9.0,
    boxOfficeMillions: 322.2,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Піаніст',
    director: 'Роман Полянський',
    releaseYear: 2002,
    runtimeMinutes: 150,
    genre: 'Драма',
    rating: 8.5,
    boxOfficeMillions: 120.1,
    isOscarWinner: true,
  }),

  // --- Нові фільми: класика, блокбастери, українське кіно ---
  new Movie({
    title: 'Оппенгеймер',
    director: 'Крістофер Нолан',
    releaseYear: 2023,
    runtimeMinutes: 180,
    genre: 'Біографія',
    rating: 8.6,
    boxOfficeMillions: 952,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Паразити',
    director: 'Пон Чжун Хо',
    releaseYear: 2019,
    runtimeMinutes: 132,
    genre: 'Комедія',
    rating: 8.5,
    boxOfficeMillions: 263.1,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Джокер',
    director: 'Тодд Філліпс',
    releaseYear: 2019,
    runtimeMinutes: 122,
    genre: 'Драма',
    rating: 8.4,
    boxOfficeMillions: 1074.3,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Сяйво',
    director: 'Стенлі Кубрик',
    releaseYear: 1980,
    runtimeMinutes: 146,
    genre: 'Жахи',
    rating: 8.4,
    boxOfficeMillions: 44,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Леон',
    director: 'Люк Бессон',
    releaseYear: 1994,
    runtimeMinutes: 110,
    genre: 'Бойовик',
    rating: 8.5,
    boxOfficeMillions: 19.5,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Назад у майбутнє',
    director: 'Роберт Земекіс',
    releaseYear: 1985,
    runtimeMinutes: 116,
    genre: 'Наукова фантастика',
    rating: 8.5,
    boxOfficeMillions: 388.8,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Володар перснів: Братство персня',
    director: 'Пітер Джексон',
    releaseYear: 2001,
    runtimeMinutes: 178,
    genre: 'Фентезі',
    rating: 8.8,
    boxOfficeMillions: 897.7,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Душа',
    director: 'Піт Доктер',
    releaseYear: 2020,
    runtimeMinutes: 100,
    genre: 'Анімація',
    rating: 8.0,
    boxOfficeMillions: 120.9,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Король Лев',
    director: 'Роджер Аллерс, Роб Мінкофф',
    releaseYear: 1994,
    runtimeMinutes: 88,
    genre: 'Анімація',
    rating: 8.5,
    boxOfficeMillions: 968.5,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Шерлок Голмс',
    director: 'Гай Річі',
    releaseYear: 2009,
    runtimeMinutes: 128,
    genre: 'Пригоди',
    rating: 7.6,
    boxOfficeMillions: 524,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Зоряні війни: Нова надія',
    director: 'Джордж Лукас',
    releaseYear: 1977,
    runtimeMinutes: 121,
    genre: 'Наукова фантастика',
    rating: 8.6,
    boxOfficeMillions: 775.8,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Прибуття',
    director: 'Дені Вільнев',
    releaseYear: 2016,
    runtimeMinutes: 116,
    genre: 'Наукова фантастика',
    rating: 7.9,
    boxOfficeMillions: 203.4,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Ла-Ла Ленд',
    director: 'Деміен Шазелл',
    releaseYear: 2016,
    runtimeMinutes: 128,
    genre: 'Мюзикл',
    rating: 8.0,
    boxOfficeMillions: 447.3,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Джанґо вільний',
    director: 'Квентін Тарантіно',
    releaseYear: 2012,
    runtimeMinutes: 165,
    genre: 'Вестерн',
    rating: 8.4,
    boxOfficeMillions: 425.4,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Маска',
    director: 'Чак Рассел',
    releaseYear: 1994,
    runtimeMinutes: 101,
    genre: 'Комедія',
    rating: 6.9,
    boxOfficeMillions: 351.6,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Парк Юрського періоду',
    director: 'Стівен Спілберг',
    releaseYear: 1993,
    runtimeMinutes: 127,
    genre: 'Пригоди',
    rating: 8.2,
    boxOfficeMillions: 1109.8,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Шоу Трумена',
    director: 'Пітер Вір',
    releaseYear: 1998,
    runtimeMinutes: 103,
    genre: 'Драма',
    rating: 8.2,
    boxOfficeMillions: 264.1,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Дюна: Частина друга',
    director: 'Дені Вільнев',
    releaseYear: 2024,
    runtimeMinutes: 166,
    genre: 'Наукова фантастика',
    rating: 8.7,
    boxOfficeMillions: 711.8,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Барбі',
    director: 'Грета Гервіг',
    releaseYear: 2023,
    runtimeMinutes: 114,
    genre: 'Комедія',
    rating: 6.9,
    boxOfficeMillions: 1445.6,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Сам удома',
    director: 'Кріс Коламбус',
    releaseYear: 1990,
    runtimeMinutes: 103,
    genre: 'Комедія',
    rating: 7.7,
    boxOfficeMillions: 476.7,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Касабланка',
    director: 'Майкл Кертіс',
    releaseYear: 1942,
    runtimeMinutes: 102,
    genre: 'Романтика',
    rating: 8.5,
    boxOfficeMillions: 4.1,
    isOscarWinner: true,
  }),
  new Movie({
    title: 'Палаюче серце',
    director: 'Олівер Стоун',
    releaseYear: 1991,
    runtimeMinutes: 191,
    genre: 'Трилер',
    rating: 8.3,
    boxOfficeMillions: 250,
    isOscarWinner: true,
  }),

  // --- Знакові українські фільми ---
  new Movie({
    title: 'Тіні забутих предків',
    director: 'Сергій Параджанов',
    releaseYear: 1965,
    runtimeMinutes: 97,
    genre: 'Драма',
    rating: 8.1,
    boxOfficeMillions: 0.1, // Умовні дані
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Земля',
    director: 'Олександр Довженко',
    releaseYear: 1930,
    runtimeMinutes: 75,
    genre: 'Драма',
    rating: 8.2,
    boxOfficeMillions: 0.05,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Кіборги',
    director: 'Ахтем Сеітаблаєв',
    releaseYear: 2017,
    runtimeMinutes: 112,
    genre: 'Військовий',
    rating: 7.9,
    boxOfficeMillions: 0.015,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Мої думки тихі',
    director: 'Антоніо Лукіч',
    releaseYear: 2019,
    runtimeMinutes: 106,
    genre: 'Комедія',
    rating: 7.7,
    boxOfficeMillions: 0.009,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Памфір',
    director: 'Дмитро Сухолиткий-Собчук',
    releaseYear: 2022,
    runtimeMinutes: 106,
    genre: 'Драма',
    rating: 7.8,
    boxOfficeMillions: 0.003,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Додому',
    director: 'Наріман Алієв',
    releaseYear: 2019,
    runtimeMinutes: 92,
    genre: 'Драма',
    rating: 7.5,
    boxOfficeMillions: 0.002,
    isOscarWinner: false,
  }),
  new Movie({
    title: 'Захар Беркут',
    director: 'Ахтем Сеітаблаєв',
    releaseYear: 2019,
    runtimeMinutes: 110,
    genre: 'Історичний',
    rating: 6.1,
    boxOfficeMillions: 0.013,
    isOscarWinner: false,
  }),

  // --- Додаткові унікальні фільми для обсягу ---
  ...Array.from({length: 1e4}).map((_, i) => {
    const genres = ['Драма', 'Комедія', 'Бойовик', 'Пригоди', 'Фантастика']
    const randomGenre = genres[Math.floor(Math.random() * genres.length)]
    const randomYear = 1950 + Math.floor(Math.random() * 75) // 1950-2025
    const randomRuntime = 90 + Math.floor(Math.random() * 90) // 90-180 хв
    const randomRating = (Math.random() * 5 + 4).toFixed(1) // 4.0 - 9.0
    const randomBoxOffice = (Math.random() * 1000 + 1).toFixed(1) // 1 - 1000 млн

    return new Movie({
      title: `Фільм-${i + 1}`,
      director: `Режисер ${i + 1}`,
      releaseYear: randomYear,
      runtimeMinutes: randomRuntime,
      genre: randomGenre,
      rating: parseFloat(randomRating),
      boxOfficeMillions: parseFloat(randomBoxOffice),
      isOscarWinner: Math.random() > 0.9,
    })
  }),
]
